# Generated by Django 6.0.6 on 2026-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongodb_id', models.CharField(max_length=24, unique=True)),
                ('token_number', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=250)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongodb_id', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('token_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(default=1, unique=True)),
                ('current_token', models.CharField(blank=True, max_length=20, null=True)),
                ('last_token_index', models.IntegerField(default=0)),
                ('average_consultation_time', models.IntegerField(default=5)),
            ],
        ),
    ]
